name: Deploy Backend to Kinsta

on:
  push:
    branches: [ main ]
    paths:
      - 'application/backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'application/backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          cd application/backend
          pnpm install
          
      - name: Build
        run: |
          cd application/backend
          pnpm build
          
      - name: Prepare for deployment
        run: |
          cd application/backend
          # Create a new package.json in the dist directory
          echo '{
            "name": "civisai-backend",
            "version": "1.0.0",
            "private": true,
            "engines": {
              "node": "20.x",
              "pnpm": "8.x"
            },
            "scripts": {
              "start": "node index.js"
            }
          }' > dist/package.json
          
          # Create a Procfile in the dist directory
          echo "web: node index.js" > dist/Procfile
          
          # Create a nixpacks.toml in the dist directory
          echo '[phases.setup]
          nixPkgs = ["nodejs_20", "pnpm-8_x"]

          [phases.install]
          cmds = ["pnpm install"]

          [phases.build]
          cmds = ["pnpm build"]

          [start]
          cmd = "node index.js"' > dist/nixpacks.toml
          
      - name: Deploy to Kinsta
        uses: kinsta/github-action-deploy@v1
        with:
          app-name: civisai-backend
          build-dir: application/backend/dist
          api-key: ${{ secrets.CIVIS_API_KEY_SEVALLA }}
          environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
          start-command: "node index.js"
          env-vars: |
            PORT=3001
            NODE_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }} 