name: Deploy Frontend to Kinsta

on:
  push:
    branches: [ main ]
    paths:
      - 'application/frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'application/frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          cd application/frontend
          pnpm install
          
      - name: Build
        run: |
          cd application/frontend
          pnpm build
        env:
          VITE_API_URL: https://civisai-ls8ws.kinsta.app
          
      - name: Create nixpacks.toml
        run: |
          cd application/frontend
          echo '[phases.setup]
          nixPkgs = ["nodejs_20", "pnpm-8_x"]

          [phases.install]
          cmds = ["pnpm install"]

          [phases.build]
          cmds = ["pnpm build"]

          [start]
          cmd = "npx serve -s dist"' > nixpacks.toml
          
      - name: Create Procfile
        run: |
          cd application/frontend
          echo "web: npx serve -s dist" > Procfile
          
      - name: Prepare for deployment
        run: |
          cd application/frontend
          # Create a new package.json for the dist directory
          echo '{
            "name": "civisai-frontend",
            "version": "1.0.0",
            "private": true,
            "engines": {
              "node": "20.x",
              "pnpm": "8.x"
            },
            "scripts": {
              "start": "npx serve -s dist"
            },
            "dependencies": {
              "serve": "^14.2.1"
            }
          }' > dist/package.json
          cp pnpm-lock.yaml dist/
          cp nixpacks.toml dist/
          cp Procfile dist/
          
      - name: Deploy to Kinsta
        uses: kinsta/github-action-deploy@v1
        with:
          app-name: civisai-frontend
          build-dir: application/frontend/dist
          api-key: ${{ secrets.CIVIS_API_KEY_SEVALLA }}
          environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
          start-command: "npx serve -s dist" 